backend:
  name: git-gateway
  branch: main
  repo: github
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
