backend:
  name: github
  branch: main
  repo: JeanMoraes/decap-cms
  auth_scope: repo
  app_id: "Ov23liR8r2JIalExorvw"
  base_url: https://decap-cms-two.vercel.app/
  auth_endpoint: "/admin/callback"
  cms_label_prefix: "MySite"
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
